on:
  workflow_dispatch:
jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "the job is running "
        if: ${{ github.event_name == 'push' || github.ref == 'refs/heads/main' }}
